"""add_indexes_user_id_and_fk_uuid

Revision ID: 1710e67a118b
Revises: 20260505_v8_2_refresh_tokens
Create Date: 2026-05-06 18:46:34.738200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1710e67a118b'
down_revision: Union[str, Sequence[str], None] = '20260505_v8_2_refresh_tokens'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_actual_workout_exercises_actual_workout_uuid'), 'actual_workout_exercises', ['actual_workout_uuid'], unique=False)
    op.create_index(op.f('ix_actual_workout_exercises_exercise_uuid'), 'actual_workout_exercises', ['exercise_uuid'], unique=False)
    op.create_index(op.f('ix_actual_workout_sets_actual_workout_exercise_uuid'), 'actual_workout_sets', ['actual_workout_exercise_uuid'], unique=False)
    op.create_index(op.f('ix_actual_workouts_user_id'), 'actual_workouts', ['user_id'], unique=False)
    op.create_index(op.f('ix_cycle_workouts_planned_workout_uuid'), 'cycle_workouts', ['planned_workout_uuid'], unique=False)
    op.create_index(op.f('ix_cycle_workouts_training_cycle_uuid'), 'cycle_workouts', ['training_cycle_uuid'], unique=False)
    op.create_index(op.f('ix_exercise_equipment_equipment_uuid'), 'exercise_equipment', ['equipment_uuid'], unique=False)
    op.create_index(op.f('ix_exercise_equipment_exercise_uuid'), 'exercise_equipment', ['exercise_uuid'], unique=False)
    op.create_index(op.f('ix_exercise_muscles_exercise_uuid'), 'exercise_muscles', ['exercise_uuid'], unique=False)
    op.create_index(op.f('ix_exercise_muscles_muscle_uuid'), 'exercise_muscles', ['muscle_uuid'], unique=False)
    op.create_index(op.f('ix_exercises_user_id'), 'exercises', ['user_id'], unique=False)
    op.create_index(op.f('ix_muscle_goals_muscle_uuid'), 'muscle_goals', ['muscle_uuid'], unique=False)
    op.create_index(op.f('ix_muscle_goals_user_id'), 'muscle_goals', ['user_id'], unique=False)
    op.create_index(op.f('ix_muscles_user_id'), 'muscles', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_planned_workout_exercises_exercise_uuid'), 'planned_workout_exercises', ['exercise_uuid'], unique=False)
    op.create_index(op.f('ix_planned_workout_exercises_planned_workout_uuid'), 'planned_workout_exercises', ['planned_workout_uuid'], unique=False)
    op.create_index(op.f('ix_planned_workouts_user_id'), 'planned_workouts', ['user_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_routine_periods_user_id'), 'routine_periods', ['user_id'], unique=False)
    op.create_index(op.f('ix_routine_task_checks_task_uuid'), 'routine_task_checks', ['task_uuid'], unique=False)
    op.create_index(op.f('ix_routine_task_checks_user_id'), 'routine_task_checks', ['user_id'], unique=False)
    op.create_index(op.f('ix_routine_tasks_period_uuid'), 'routine_tasks', ['period_uuid'], unique=False)
    op.create_index(op.f('ix_routine_tasks_user_id'), 'routine_tasks', ['user_id'], unique=False)
    op.create_index(op.f('ix_superset_exercises_exercise_uuid'), 'superset_exercises', ['exercise_uuid'], unique=False)
    op.create_index(op.f('ix_superset_exercises_superset_group_uuid'), 'superset_exercises', ['superset_group_uuid'], unique=False)
    op.create_index(op.f('ix_superset_groups_user_id'), 'superset_groups', ['user_id'], unique=False)
    op.create_index(op.f('ix_training_cycles_user_id'), 'training_cycles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_cycles_user_id'), table_name='training_cycles')
    op.drop_index(op.f('ix_superset_groups_user_id'), table_name='superset_groups')
    op.drop_index(op.f('ix_superset_exercises_superset_group_uuid'), table_name='superset_exercises')
    op.drop_index(op.f('ix_superset_exercises_exercise_uuid'), table_name='superset_exercises')
    op.drop_index(op.f('ix_routine_tasks_user_id'), table_name='routine_tasks')
    op.drop_index(op.f('ix_routine_tasks_period_uuid'), table_name='routine_tasks')
    op.drop_index(op.f('ix_routine_task_checks_user_id'), table_name='routine_task_checks')
    op.drop_index(op.f('ix_routine_task_checks_task_uuid'), table_name='routine_task_checks')
    op.drop_index(op.f('ix_routine_periods_user_id'), table_name='routine_periods')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_planned_workouts_user_id'), table_name='planned_workouts')
    op.drop_index(op.f('ix_planned_workout_exercises_planned_workout_uuid'), table_name='planned_workout_exercises')
    op.drop_index(op.f('ix_planned_workout_exercises_exercise_uuid'), table_name='planned_workout_exercises')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_muscles_user_id'), table_name='muscles')
    op.drop_index(op.f('ix_muscle_goals_user_id'), table_name='muscle_goals')
    op.drop_index(op.f('ix_muscle_goals_muscle_uuid'), table_name='muscle_goals')
    op.drop_index(op.f('ix_exercises_user_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercise_muscles_muscle_uuid'), table_name='exercise_muscles')
    op.drop_index(op.f('ix_exercise_muscles_exercise_uuid'), table_name='exercise_muscles')
    op.drop_index(op.f('ix_exercise_equipment_exercise_uuid'), table_name='exercise_equipment')
    op.drop_index(op.f('ix_exercise_equipment_equipment_uuid'), table_name='exercise_equipment')
    op.drop_index(op.f('ix_cycle_workouts_training_cycle_uuid'), table_name='cycle_workouts')
    op.drop_index(op.f('ix_cycle_workouts_planned_workout_uuid'), table_name='cycle_workouts')
    op.drop_index(op.f('ix_actual_workouts_user_id'), table_name='actual_workouts')
    op.drop_index(op.f('ix_actual_workout_sets_actual_workout_exercise_uuid'), table_name='actual_workout_sets')
    op.drop_index(op.f('ix_actual_workout_exercises_exercise_uuid'), table_name='actual_workout_exercises')
    op.drop_index(op.f('ix_actual_workout_exercises_actual_workout_uuid'), table_name='actual_workout_exercises')
    # ### end Alembic commands ###
