"""f8q4_unique_exercises_user_id_name

Revision ID: 3ec81eb456a1
Revises: f72_reload_fn
Create Date: 2026-05-06 21:24:54.364700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ec81eb456a1'
down_revision: Union[str, Sequence[str], None] = 'f72_reload_fn'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_exercises_user_id_name', 'exercises', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_exercises_user_id_name', 'exercises', type_='unique')
    # ### end Alembic commands ###
